Update auto_merge.yml

diff --git a/.github/workflows/auto_merge.yml b/.github/workflows/auto_merge.yml
--- a/.github/workflows/auto_merge.yml
+++ b/.github/workflows/auto_merge.yml
@@ -27,6 +27,6 @@ jobs:
           else
             for PR_NUMBER in $PR_NUMBERS; do
               echo "Attempting to merge PR #$PR_NUMBER"
-              gh pr merge "$PR_NUMBER" --auto --merge || echo "Failed to merge PR #$PR_NUMBER, but continuing..."
+              gh pr merge "$PR_NUMBER" --merge || echo "Failed to merge PR #$PR_NUMBER, but continuing..."
             done
           fi
